#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BunnyBeamLevelData

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BunnyBeamLevelData.BunnyBeamLevelData
// 0x0018 (0x0018 - 0x0000)
struct FBunnyBeamLevelData final
{
public:
	class FName                                   TagName_25_CF4FCEF943349D3C19FEC79CF4BDCED0;       // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChargeTime_27_0B3A25AD4F681B1170494889326E2404;    // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DamageRatio_22_5378728D4802F3547C23A08B174AB84F;   // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

