#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BunnyGaugeDeltaApplyPolicy

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum BunnyGaugeDeltaApplyPolicy.BunnyGaugeDeltaApplyPolicy
// NumValues: 0x0003
enum class EBunnyGaugeDeltaApplyPolicy : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	BunnyGaugeDeltaApplyPolicy_MAX           = 2,
};

}

