#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CAM_PC_Skill_AtkShake_11

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CAM_PC_Skill_AtkShake_11.CAM_PC_Skill_AtkShake_11_C
// 0x0000 (0x01A0 - 0x01A0)
class UCAM_PC_Skill_AtkShake_11_C final : public UM1MoveCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CAM_PC_Skill_AtkShake_11_C">();
	}
	static class UCAM_PC_Skill_AtkShake_11_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCAM_PC_Skill_AtkShake_11_C>();
	}
};

}

