#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dagger_Rune

#include "Basic.hpp"

#include "Default_Fist_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dagger_Rune.Dagger_Rune_C
// 0x0000 (0x04F0 - 0x04F0)
class UDagger_Rune_C final : public UDefault_Fist_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Dagger_Rune_C">();
	}
	static class UDagger_Rune_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDagger_Rune_C>();
	}
};

}

