#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_LNC_1006

#include "Basic.hpp"

#include "F_LNC_structs.hpp"


namespace SDK
{

// ScriptStruct F_LNC_1006.F_LNC_1006_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct F_LNC_1006::FAnimBlueprintGeneratedConstantData final : public F_LNC::FAnimBlueprintGeneratedConstantData
{
};

}

