#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_LNC

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_LNC.F_LNC_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_LNC_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_LNC_C">();
	}
	static class UF_LNC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_LNC_C>();
	}
};

}

