#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_LNC_1006

#include "Basic.hpp"

#include "F_LNC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_LNC_1006.F_LNC_1006_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_LNC_1006_C final : public UF_LNC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_LNC_1006_C">();
	}
	static class UF_LNC_1006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_LNC_1006_C>();
	}
};

}

