#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MG_1005

#include "Basic.hpp"

#include "F_MG_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MG_1005.F_MG_1005_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_MG_1005_C final : public UF_MG_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MG_1005_C">();
	}
	static class UF_MG_1005_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MG_1005_C>();
	}
};

}

