#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MG

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MG.F_MG_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_MG_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MG_C">();
	}
	static class UF_MG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MG_C>();
	}
};

}

