#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MG_1003

#include "Basic.hpp"

#include "F_MG_structs.hpp"


namespace SDK
{

// ScriptStruct F_MG_1003.F_MG_1003_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct F_MG_1003::FAnimBlueprintGeneratedConstantData final : public F_MG::FAnimBlueprintGeneratedConstantData
{
};

}

