#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_SCR_1001

#include "Basic.hpp"

#include "F_SCR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_SCR_1001.F_SCR_1001_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_SCR_1001_C final : public UF_SCR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_SCR_1001_C">();
	}
	static class UF_SCR_1001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_SCR_1001_C>();
	}
};

}

