#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Invasion_EnergyEmitter_0

#include "Basic.hpp"

#include "BR_structs.hpp"


namespace SDK
{

// ScriptStruct Invasion_EnergyEmitter.Invasion_EnergyEmitter_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct Invasion_EnergyEmitter_0::FAnimBlueprintGeneratedConstantData final : public BR::FAnimBlueprintGeneratedConstantData
{
};

}

