#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass LNC.LNC_C
// 0x0000 (0x1CD0 - 0x1CD0)
class ULNC_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNC_C">();
	}
	static class ULNC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULNC_C>();
	}
};

}

