#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1006_0

#include "Basic.hpp"

#include "LNC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass LNC_1006.LNC_1006_C
// 0x0000 (0x1CD0 - 0x1CD0)
class ULNC_1006_C final : public ULNC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNC_1006_C">();
	}
	static class ULNC_1006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULNC_1006_C>();
	}
};

}

