#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1006_0

#include "Basic.hpp"

#include "LNC_structs.hpp"


namespace SDK
{

// ScriptStruct LNC_1006.LNC_1006_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct LNC_1006_0::FAnimBlueprintGeneratedConstantData final : public LNC::FAnimBlueprintGeneratedConstantData
{
};

}

