#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1006

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LNC_1006.LNC_1006_C
// 0x0020 (0x0498 - 0x0478)
class ALNC_1006_C final : public AM1Weapon
{
public:
	class UM1WeaponFireLoopComponent*             M1WeaponFireLoop;                                  // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponMagazineReloadComponent*       M1WeaponMagazineReload;                            // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponGuideVfxComponent*             M1WeaponGuideVfx;                                  // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponLauncherComponent*             M1WeaponLauncher;                                  // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNC_1006_C">();
	}
	static class ALNC_1006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALNC_1006_C>();
	}
};

}

