#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC

#include "Basic.hpp"

#include "UpperBody_structs.hpp"


namespace SDK
{

// ScriptStruct LNC.LNC_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct LNC::FAnimBlueprintGeneratedConstantData : public UpperBody::FAnimBlueprintGeneratedConstantData
{
};

}

