#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNCCommonExplosionCameraShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LNCCommonExplosionCameraShake.LNCCommonExplosionCameraShake_C
// 0x0000 (0x01A0 - 0x01A0)
class ULNCCommonExplosionCameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNCCommonExplosionCameraShake_C">();
	}
	static class ULNCCommonExplosionCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULNCCommonExplosionCameraShake_C>();
	}
};

}

