#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNCRestoredRelicProjectile

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LNCRestoredRelicProjectile.LNCRestoredRelicProjectile_C
// 0x0000 (0x0C38 - 0x0C38)
class ALNCRestoredRelicProjectile_C final : public AM1AbilityProjectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNCRestoredRelicProjectile_C">();
	}
	static class ALNCRestoredRelicProjectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALNCRestoredRelicProjectile_C>();
	}
};

}

