#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Locomotion_2LT_F_Bunny

#include "Basic.hpp"

#include "Locomotion_2LT_F_structs.hpp"


namespace SDK
{

// ScriptStruct Locomotion_2LT_F_Bunny.Locomotion_2LT_F_Bunny_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0298 - 0x0298)
struct Locomotion_2LT_F_Bunny::FAnimBlueprintGeneratedConstantData final : public Locomotion_2LT_F::FAnimBlueprintGeneratedConstantData
{
};

}

