#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Locomotion_2LT_F_Bunny

#include "Basic.hpp"

#include "Locomotion_2LT_F_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Locomotion_2LT_F_Bunny.Locomotion_2LT_F_Bunny_C
// 0x0000 (0x2A60 - 0x2A60)
class ULocomotion_2LT_F_Bunny_C final : public ULocomotion_2LT_F_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Locomotion_2LT_F_Bunny_C">();
	}
	static class ULocomotion_2LT_F_Bunny_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULocomotion_2LT_F_Bunny_C>();
	}
};

}

