#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MG_1005

#include "Basic.hpp"

#include "MG_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass MG_1005.MG_1005_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UMG_1005_C final : public UMG_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MG_1005_C">();
	}
	static class UMG_1005_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMG_1005_C>();
	}
};

}

