#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MG_1005

#include "Basic.hpp"

#include "MG_structs.hpp"


namespace SDK
{

// ScriptStruct MG_1005.MG_1005_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct MG_1005::FAnimBlueprintGeneratedConstantData final : public MG::FAnimBlueprintGeneratedConstantData
{
};

}

