#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MG

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass MG.MG_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UMG_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MG_C">();
	}
	static class UMG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMG_C>();
	}
};

}

