#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_Subskill_Hard_RightdownToLeftup

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PC_Subskill_Hard_RightdownToLeftup.PC_Subskill_Hard_RightdownToLeftup_C
// 0x0000 (0x01A0 - 0x01A0)
class UPC_Subskill_Hard_RightdownToLeftup_C final : public UM1HitCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PC_Subskill_Hard_RightdownToLeftup_C">();
	}
	static class UPC_Subskill_Hard_RightdownToLeftup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPC_Subskill_Hard_RightdownToLeftup_C>();
	}
};

}

