#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_11_RestoredRelic

#include "Basic.hpp"

#include "PerkAbility_11_RestoredRelic_classes.hpp"
#include "PerkAbility_11_RestoredRelic_parameters.hpp"


namespace SDK
{

// Function PerkAbility_11_RestoredRelic.PerkAbility_11_RestoredRelic_C.OnAbilityEvent_199D4CC44731338852820AA9BF3D8625
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_11_RestoredRelic_C::OnAbilityEvent_199D4CC44731338852820AA9BF3D8625(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_11_RestoredRelic_C", "OnAbilityEvent_199D4CC44731338852820AA9BF3D8625");

	Params::PerkAbility_11_RestoredRelic_C_OnAbilityEvent_199D4CC44731338852820AA9BF3D8625 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_11_RestoredRelic.PerkAbility_11_RestoredRelic_C.ExecuteUbergraph_PerkAbility_11_RestoredRelic
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_11_RestoredRelic_C::ExecuteUbergraph_PerkAbility_11_RestoredRelic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_11_RestoredRelic_C", "ExecuteUbergraph_PerkAbility_11_RestoredRelic");

	Params::PerkAbility_11_RestoredRelic_C_ExecuteUbergraph_PerkAbility_11_RestoredRelic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_11_RestoredRelic.PerkAbility_11_RestoredRelic_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_11_RestoredRelic_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_11_RestoredRelic_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

