#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_3_GreatLegacy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "PerkAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PerkAbility_3_GreatLegacy.PerkAbility_3_GreatLegacy_C
// 0x0010 (0x02D8 - 0x02C8)
class UPerkAbility_3_GreatLegacy_C final : public UPerkAbilityBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PerkAbility_3_GreatLegacy_C;        // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           IgniteTag;                                         // 0x02D0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void OnEvent_FF8D19174F054E56080CDBB2055AEF7A(const struct FM1CalcDamageInfo& DamageInfo);
	void OnAbilityEvent_81077A4E43FE1CFCBC39DD89463BAD78(const struct FM1AbilityEvent& Event);
	void ExecuteUbergraph_PerkAbility_3_GreatLegacy(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PerkAbility_3_GreatLegacy_C">();
	}
	static class UPerkAbility_3_GreatLegacy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerkAbility_3_GreatLegacy_C>();
	}
};

}

