#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_3_GreatLegacy

#include "Basic.hpp"

#include "PerkAbility_3_GreatLegacy_classes.hpp"
#include "PerkAbility_3_GreatLegacy_parameters.hpp"


namespace SDK
{

// Function PerkAbility_3_GreatLegacy.PerkAbility_3_GreatLegacy_C.OnEvent_FF8D19174F054E56080CDBB2055AEF7A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1CalcDamageInfo                DamageInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UPerkAbility_3_GreatLegacy_C::OnEvent_FF8D19174F054E56080CDBB2055AEF7A(const struct FM1CalcDamageInfo& DamageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_3_GreatLegacy_C", "OnEvent_FF8D19174F054E56080CDBB2055AEF7A");

	Params::PerkAbility_3_GreatLegacy_C_OnEvent_FF8D19174F054E56080CDBB2055AEF7A Parms{};

	Parms.DamageInfo = std::move(DamageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_3_GreatLegacy.PerkAbility_3_GreatLegacy_C.OnAbilityEvent_81077A4E43FE1CFCBC39DD89463BAD78
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_3_GreatLegacy_C::OnAbilityEvent_81077A4E43FE1CFCBC39DD89463BAD78(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_3_GreatLegacy_C", "OnAbilityEvent_81077A4E43FE1CFCBC39DD89463BAD78");

	Params::PerkAbility_3_GreatLegacy_C_OnAbilityEvent_81077A4E43FE1CFCBC39DD89463BAD78 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_3_GreatLegacy.PerkAbility_3_GreatLegacy_C.ExecuteUbergraph_PerkAbility_3_GreatLegacy
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_3_GreatLegacy_C::ExecuteUbergraph_PerkAbility_3_GreatLegacy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_3_GreatLegacy_C", "ExecuteUbergraph_PerkAbility_3_GreatLegacy");

	Params::PerkAbility_3_GreatLegacy_C_ExecuteUbergraph_PerkAbility_3_GreatLegacy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_3_GreatLegacy.PerkAbility_3_GreatLegacy_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_3_GreatLegacy_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_3_GreatLegacy_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

