#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_2_ThunderCage

#include "Basic.hpp"

#include "PerkAbility_2_ThunderCage_classes.hpp"
#include "PerkAbility_2_ThunderCage_parameters.hpp"


namespace SDK
{

// Function PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C.TryAOEDamageChance
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bReturn                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_2_ThunderCage_C::TryAOEDamageChance(bool* bReturn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_2_ThunderCage_C", "TryAOEDamageChance");

	Params::PerkAbility_2_ThunderCage_C_TryAOEDamageChance Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bReturn != nullptr)
		*bReturn = Parms.bReturn;
}


// Function PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C.OnEvent_21E73C724FB6B451418F938FB3312CF6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1CalcDamageInfo                DamageInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UPerkAbility_2_ThunderCage_C::OnEvent_21E73C724FB6B451418F938FB3312CF6(const struct FM1CalcDamageInfo& DamageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_2_ThunderCage_C", "OnEvent_21E73C724FB6B451418F938FB3312CF6");

	Params::PerkAbility_2_ThunderCage_C_OnEvent_21E73C724FB6B451418F938FB3312CF6 Parms{};

	Parms.DamageInfo = std::move(DamageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C.MakeDamageFxParam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FM1FXParam                       M1FXParam                                              (Parm, OutParm)

void UPerkAbility_2_ThunderCage_C::MakeDamageFxParam(struct FM1FXParam* M1FXParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_2_ThunderCage_C", "MakeDamageFxParam");

	Params::PerkAbility_2_ThunderCage_C_MakeDamageFxParam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (M1FXParam != nullptr)
		*M1FXParam = std::move(Parms.M1FXParam);
}


// Function PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C.ExecuteUbergraph_PerkAbility_2_ThunderCage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_2_ThunderCage_C::ExecuteUbergraph_PerkAbility_2_ThunderCage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_2_ThunderCage_C", "ExecuteUbergraph_PerkAbility_2_ThunderCage");

	Params::PerkAbility_2_ThunderCage_C_ExecuteUbergraph_PerkAbility_2_ThunderCage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_2_ThunderCage_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_2_ThunderCage_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

