#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_11_RestoredRelic

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PerkAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PerkAbility_11_RestoredRelic.PerkAbility_11_RestoredRelic_C
// 0x0018 (0x02E0 - 0x02C8)
class UPerkAbility_11_RestoredRelic_C final : public UPerkAbilityBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PerkAbility_11_RestoredRelic_C;     // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   AltProjectileDataRowName;                          // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChangeChance;                                      // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnAbilityEvent_199D4CC44731338852820AA9BF3D8625(const struct FM1AbilityEvent& Event);
	void ExecuteUbergraph_PerkAbility_11_RestoredRelic(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PerkAbility_11_RestoredRelic_C">();
	}
	static class UPerkAbility_11_RestoredRelic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerkAbility_11_RestoredRelic_C>();
	}
};

}

