#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_2_ThunderCage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PerkAbilityBase_classes.hpp"
#include "M1Data_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PerkAbility_2_ThunderCage.PerkAbility_2_ThunderCage_C
// 0x0020 (0x02E8 - 0x02C8)
class UPerkAbility_2_ThunderCage_C final : public UPerkAbilityBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PerkAbility_2_ThunderCage_C;        // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        DamageChance;                                      // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Radius;                                            // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       WeaponDamage;                                      // 0x02E0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void TryAOEDamageChance(bool* bReturn);
	void OnEvent_21E73C724FB6B451418F938FB3312CF6(const struct FM1CalcDamageInfo& DamageInfo);
	void MakeDamageFxParam(struct FM1FXParam* M1FXParam);
	void ExecuteUbergraph_PerkAbility_2_ThunderCage(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PerkAbility_2_ThunderCage_C">();
	}
	static class UPerkAbility_2_ThunderCage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerkAbility_2_ThunderCage_C>();
	}
};

}

