#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PROJ_FollowerGrenadierGunfire

#include "Basic.hpp"

#include "PROJ_MonsterGunfire_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PROJ_FollowerGrenadierGunfire.PROJ_FollowerGrenadierGunfire_C
// 0x0000 (0x0C40 - 0x0C40)
class APROJ_FollowerGrenadierGunfire_C final : public APROJ_MonsterGunfire_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PROJ_FollowerGrenadierGunfire_C">();
	}
	static class APROJ_FollowerGrenadierGunfire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APROJ_FollowerGrenadierGunfire_C>();
	}
};

}

