#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SCR_1001

#include "Basic.hpp"

#include "SCR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SCR_1001.SCR_1001_C
// 0x0000 (0x1CD0 - 0x1CD0)
class USCR_1001_C final : public USCR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SCR_1001_C">();
	}
	static class USCR_1001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USCR_1001_C>();
	}
};

}

