#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SCR_1001

#include "Basic.hpp"

#include "SCR_structs.hpp"


namespace SDK
{

// ScriptStruct SCR_1001.SCR_1001_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct SCR_1001::FAnimBlueprintGeneratedConstantData final : public SCR::FAnimBlueprintGeneratedConstantData
{
};

}

