#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_TickCostByValue

#include "Basic.hpp"

#include "SE_Bunny_GaugeDeltaByValue_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_Bunny_TickCostByValue.SE_Bunny_TickCostByValue_C
// 0x0008 (0x0368 - 0x0360)
class USE_Bunny_TickCostByValue_C final : public USE_Bunny_GaugeDeltaByValue_C
{
public:
	bool                                          bDepleted;                                         // 0x0360(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void OnRep_bDepleted();
	void ExecuteTickOperation(const struct FM1AbilityOperationParam& OpParam);
	void ExecutePeriodOperation(const struct FM1AbilityOperationParam& OpParam);

	void MakeTickOpParam(double OpValue, struct FM1AbilityOperationParam* OpParam) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SE_Bunny_TickCostByValue_C">();
	}
	static class USE_Bunny_TickCostByValue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_Bunny_TickCostByValue_C>();
	}
};

}

