#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_GaugeDeltaBase

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "M1_structs.hpp"


namespace SDK::Params
{

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.OnActiveTick
// 0x0004 (0x0004 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_OnActiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.GetTickRate
// 0x0008 (0x0008 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_GetTickRate final
{
public:
	double                                        TickRate;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.ExecuteUbergraph_SE_Bunny_GaugeDeltaBase
// 0x01D8 (0x01D8 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_ExecuteUbergraph_SE_Bunny_GaugeDeltaBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanApplyOperation_bCanApply;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanApplyOperation_bShouldConsume__Periodic_Only_; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCancelled;                           // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13[0x1];                                       // 0x0013(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_DeltaSeconds;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanPerformTick_bCanApply;                 // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetTickRate_TickRate;                     // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_OnTickValue;                    // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityOperationParam               CallFunc_MakeTickOpParam_OpParam;                  // 0x0038(0x00B0)(ContainsInstancedReference)
	double                                        K2Node_CustomEvent_AccumulatedValue;               // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityOperationParam               CallFunc_MakePeriodOpParam_M1AbilityOperationParam; // 0x00F0(0x00B0)(ContainsInstancedReference)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_1;              // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BB[0x1];                                      // 0x01BB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(float DeltaSeconds)>           K2Node_CreateDelegate_OutputDelegate;              // 0x01BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanApplyOperation_bCanApply_1;            // 0x01CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanApplyOperation_bShouldConsume__Periodic_Only__1; // 0x01CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CE[0x2];                                      // 0x01CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.ExecuteTickOperation
// 0x00B0 (0x00B0 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_ExecuteTickOperation final
{
public:
	struct FM1AbilityOperationParam               OpParam;                                           // 0x0000(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.ExecutePeriodOperation
// 0x00B0 (0x00B0 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_ExecutePeriodOperation final
{
public:
	struct FM1AbilityOperationParam               OpParam;                                           // 0x0000(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.BP_OnDeactivated
// 0x0001 (0x0001 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_BP_OnDeactivated final
{
public:
	bool                                          bCancelled;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.Auth_ApplyOnTick
// 0x0008 (0x0008 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_Auth_ApplyOnTick final
{
public:
	double                                        OnTickValue;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.Auth_ApplyOnPeriod
// 0x0008 (0x0008 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_Auth_ApplyOnPeriod final
{
public:
	double                                        AccumulatedValue;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.MakeTickOpParam
// 0x0208 (0x0208 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_MakeTickOpParam final
{
public:
	double                                        OpValue;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityOperationParam               OpParam;                                           // 0x0008(0x00B0)(Parm, OutParm, ContainsInstancedReference)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue;          // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue;            // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData;              // 0x00D8(0x0020)()
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData_1;            // 0x00F8(0x0020)()
	class FString                                 CallFunc_GetStatEnumString_ReturnValue;            // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData_2;            // 0x0128(0x0020)()
	TArray<struct FM1AbilityParamData>            K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ReferenceParm)
	struct FM1AbilityOperationParam               K2Node_MakeStruct_M1AbilityOperationParam;         // 0x0158(0x00B0)(ContainsInstancedReference)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.MakePeriodOpParam
// 0x01D8 (0x01D8 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_MakePeriodOpParam final
{
public:
	double                                        InDouble;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityOperationParam               M1AbilityOperationParam;                           // 0x0008(0x00B0)(Parm, OutParm, ContainsInstancedReference)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue;          // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetStatEnumString_ReturnValue;            // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData;              // 0x00D8(0x0020)()
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData_1;            // 0x00F8(0x0020)()
	TArray<struct FM1AbilityParamData>            K2Node_MakeArray_Array;                            // 0x0118(0x0010)(ReferenceParm)
	struct FM1AbilityOperationParam               K2Node_MakeStruct_M1AbilityOperationParam;         // 0x0128(0x00B0)(ContainsInstancedReference)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.GetCurrentTickAccumulatedValue
// 0x0008 (0x0008 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_GetCurrentTickAccumulatedValue final
{
public:
	double                                        CurrentTickAccumulatedValue;                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.CanPerformTick
// 0x0001 (0x0001 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_CanPerformTick final
{
public:
	bool                                          bCanApply;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_GaugeDeltaBase.SE_Bunny_GaugeDeltaBase_C.CanApplyOperation
// 0x0002 (0x0002 - 0x0000)
struct SE_Bunny_GaugeDeltaBase_C_CanApplyOperation final
{
public:
	bool                                          bCanApply;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bShouldConsume__Periodic_Only_;                    // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

