#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_IncreaseCommonGaugeByPassive

#include "Basic.hpp"

#include "SE_Bunny_IncreaseCommonGaugeByPassive_classes.hpp"
#include "SE_Bunny_IncreaseCommonGaugeByPassive_parameters.hpp"


namespace SDK
{

// Function SE_Bunny_IncreaseCommonGaugeByPassive.SE_Bunny_IncreaseCommonGaugeByPassive_C.OnActiveTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_IncreaseCommonGaugeByPassive_C::OnActiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeByPassive_C", "OnActiveTick");

	Params::SE_Bunny_IncreaseCommonGaugeByPassive_C_OnActiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_IncreaseCommonGaugeByPassive.SE_Bunny_IncreaseCommonGaugeByPassive_C.ExecuteUbergraph_SE_Bunny_IncreaseCommonGaugeByPassive
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_IncreaseCommonGaugeByPassive_C::ExecuteUbergraph_SE_Bunny_IncreaseCommonGaugeByPassive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeByPassive_C", "ExecuteUbergraph_SE_Bunny_IncreaseCommonGaugeByPassive");

	Params::SE_Bunny_IncreaseCommonGaugeByPassive_C_ExecuteUbergraph_SE_Bunny_IncreaseCommonGaugeByPassive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_IncreaseCommonGaugeByPassive.SE_Bunny_IncreaseCommonGaugeByPassive_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_IncreaseCommonGaugeByPassive_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeByPassive_C", "BP_OnDeactivated");

	Params::SE_Bunny_IncreaseCommonGaugeByPassive_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_IncreaseCommonGaugeByPassive.SE_Bunny_IncreaseCommonGaugeByPassive_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USE_Bunny_IncreaseCommonGaugeByPassive_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeByPassive_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

