#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_IncreaseCommonGaugeBase

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "SE_Bunny_GaugeDeltaByDisplacement_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_Bunny_IncreaseCommonGaugeBase.SE_Bunny_IncreaseCommonGaugeBase_C
// 0x0000 (0x0360 - 0x0360)
class USE_Bunny_IncreaseCommonGaugeBase_C : public USE_Bunny_GaugeDeltaByDisplacement_C
{
public:
	void GetTickRate(double* TickRate);

	void CanPerformTick(bool* bCanApply) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SE_Bunny_IncreaseCommonGaugeBase_C">();
	}
	static class USE_Bunny_IncreaseCommonGaugeBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_Bunny_IncreaseCommonGaugeBase_C>();
	}
};

}

