#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_Pulsar

#include "Basic.hpp"

#include "SE_Bunny_Pulsar_classes.hpp"
#include "SE_Bunny_Pulsar_parameters.hpp"


namespace SDK
{

// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.TickAccumulateDistance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bApplyEffect                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::TickAccumulateDistance(double DeltaSeconds, bool* bApplyEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "TickAccumulateDistance");

	Params::SE_Bunny_Pulsar_C_TickAccumulateDistance Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);

	if (bApplyEffect != nullptr)
		*bApplyEffect = Parms.bApplyEffect;
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.OnUpdate_0F9E177B46800FE31843C08B66F77852
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::OnUpdate_0F9E177B46800FE31843C08B66F77852(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "OnUpdate_0F9E177B46800FE31843C08B66F77852");

	Params::SE_Bunny_Pulsar_C_OnUpdate_0F9E177B46800FE31843C08B66F77852 Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.OnEvent_95E10CBB482C72537A93E39DD928EE25
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     InTag                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    InAdded                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::OnEvent_95E10CBB482C72537A93E39DD928EE25(const struct FGameplayTag& InTag, bool InAdded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "OnEvent_95E10CBB482C72537A93E39DD928EE25");

	Params::SE_Bunny_Pulsar_C_OnEvent_95E10CBB482C72537A93E39DD928EE25 Parms{};

	Parms.InTag = std::move(InTag);
	Parms.InAdded = InAdded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.OnEvent_6752D6AC4B631E4A1F9135B3CFBF327A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     InTag                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    InAdded                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::OnEvent_6752D6AC4B631E4A1F9135B3CFBF327A(const struct FGameplayTag& InTag, bool InAdded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "OnEvent_6752D6AC4B631E4A1F9135B3CFBF327A");

	Params::SE_Bunny_Pulsar_C_OnEvent_6752D6AC4B631E4A1F9135B3CFBF327A Parms{};

	Parms.InTag = std::move(InTag);
	Parms.InAdded = InAdded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.ExecuteUbergraph_SE_Bunny_Pulsar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::ExecuteUbergraph_SE_Bunny_Pulsar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "ExecuteUbergraph_SE_Bunny_Pulsar");

	Params::SE_Bunny_Pulsar_C_ExecuteUbergraph_SE_Bunny_Pulsar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "BP_OnDeactivated");

	Params::SE_Bunny_Pulsar_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USE_Bunny_Pulsar_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SE_Bunny_Pulsar.SE_Bunny_Pulsar_C.Auth_Explode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsActivation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_Pulsar_C::Auth_Explode(bool bIsActivation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_Pulsar_C", "Auth_Explode");

	Params::SE_Bunny_Pulsar_C_Auth_Explode Parms{};

	Parms.bIsActivation = bIsActivation;

	UObject::ProcessEvent(Func, &Parms);
}

}

