#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_IncreaseCommonGaugeBase

#include "Basic.hpp"

#include "SE_Bunny_IncreaseCommonGaugeBase_classes.hpp"
#include "SE_Bunny_IncreaseCommonGaugeBase_parameters.hpp"


namespace SDK
{

// Function SE_Bunny_IncreaseCommonGaugeBase.SE_Bunny_IncreaseCommonGaugeBase_C.GetTickRate
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TickRate                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_IncreaseCommonGaugeBase_C::GetTickRate(double* TickRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeBase_C", "GetTickRate");

	Params::SE_Bunny_IncreaseCommonGaugeBase_C_GetTickRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TickRate != nullptr)
		*TickRate = Parms.TickRate;
}


// Function SE_Bunny_IncreaseCommonGaugeBase.SE_Bunny_IncreaseCommonGaugeBase_C.CanPerformTick
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    bCanApply                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_IncreaseCommonGaugeBase_C::CanPerformTick(bool* bCanApply) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_IncreaseCommonGaugeBase_C", "CanPerformTick");

	Params::SE_Bunny_IncreaseCommonGaugeBase_C_CanPerformTick Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bCanApply != nullptr)
		*bCanApply = Parms.bCanApply;
}

}

