#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_Shock

#include "Basic.hpp"

#include "SimpleStatusEffect_VFXPlay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_Bunny_Shock.SE_Bunny_Shock_C
// 0x0000 (0x03A8 - 0x03A8)
class USE_Bunny_Shock_C final : public USimpleStatusEffect_VFXPlay_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SE_Bunny_Shock_C">();
	}
	static class USE_Bunny_Shock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_Bunny_Shock_C>();
	}
};

}

