#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_DecreaseCommonGaugeByPassive

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function SE_Bunny_DecreaseCommonGaugeByPassive.SE_Bunny_DecreaseCommonGaugeByPassive_C.ExecuteUbergraph_SE_Bunny_DecreaseCommonGaugeByPassive
// 0x0010 (0x0010 - 0x0000)
struct SE_Bunny_DecreaseCommonGaugeByPassive_C_ExecuteUbergraph_SE_Bunny_DecreaseCommonGaugeByPassive final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCancelled;                           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_DecreaseCommonGaugeByPassive.SE_Bunny_DecreaseCommonGaugeByPassive_C.BP_OnDeactivated
// 0x0001 (0x0001 - 0x0000)
struct SE_Bunny_DecreaseCommonGaugeByPassive_C_BP_OnDeactivated final
{
public:
	bool                                          bCancelled;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SE_Bunny_DecreaseCommonGaugeByPassive.SE_Bunny_DecreaseCommonGaugeByPassive_C.CanPerformTick
// 0x0020 (0x0020 - 0x0000)
struct SE_Bunny_DecreaseCommonGaugeByPassive_C_CanPerformTick final
{
public:
	bool                                          bCanApply;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Vector_IsZero_ReturnValue;                // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

