#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_GaugeDeltaByMaxRatio

#include "Basic.hpp"

#include "SE_Bunny_GaugeDeltaByMaxRatio_classes.hpp"
#include "SE_Bunny_GaugeDeltaByMaxRatio_parameters.hpp"


namespace SDK
{

// Function SE_Bunny_GaugeDeltaByMaxRatio.SE_Bunny_GaugeDeltaByMaxRatio_C.GetTickRate
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TickRate                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_GaugeDeltaByMaxRatio_C::GetTickRate(double* TickRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_GaugeDeltaByMaxRatio_C", "GetTickRate");

	Params::SE_Bunny_GaugeDeltaByMaxRatio_C_GetTickRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TickRate != nullptr)
		*TickRate = Parms.TickRate;
}


// Function SE_Bunny_GaugeDeltaByMaxRatio.SE_Bunny_GaugeDeltaByMaxRatio_C.ExecuteUbergraph_SE_Bunny_GaugeDeltaByMaxRatio
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_GaugeDeltaByMaxRatio_C::ExecuteUbergraph_SE_Bunny_GaugeDeltaByMaxRatio(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_GaugeDeltaByMaxRatio_C", "ExecuteUbergraph_SE_Bunny_GaugeDeltaByMaxRatio");

	Params::SE_Bunny_GaugeDeltaByMaxRatio_C_ExecuteUbergraph_SE_Bunny_GaugeDeltaByMaxRatio Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SE_Bunny_GaugeDeltaByMaxRatio.SE_Bunny_GaugeDeltaByMaxRatio_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USE_Bunny_GaugeDeltaByMaxRatio_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_GaugeDeltaByMaxRatio_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

