#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_Pulsar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_Bunny_Pulsar.SE_Bunny_Pulsar_C
// 0x0038 (0x0370 - 0x0338)
class USE_Bunny_Pulsar_C final : public UM1StatusEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        Dur_Duration;                                      // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AccumulatedMovementDistance;                       // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AOE_Radius;                                        // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Distance;                                          // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEvading;                                          // 0x0360(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361[0x3];                                      // 0x0361(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                PrevLocation;                                      // 0x0364(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void TickAccumulateDistance(double DeltaSeconds, bool* bApplyEffect);
	void OnUpdate_0F9E177B46800FE31843C08B66F77852(float DeltaTime);
	void OnEvent_95E10CBB482C72537A93E39DD928EE25(const struct FGameplayTag& InTag, bool InAdded);
	void OnEvent_6752D6AC4B631E4A1F9135B3CFBF327A(const struct FGameplayTag& InTag, bool InAdded);
	void ExecuteUbergraph_SE_Bunny_Pulsar(int32 EntryPoint);
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();
	void Auth_Explode(bool bIsActivation);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SE_Bunny_Pulsar_C">();
	}
	static class USE_Bunny_Pulsar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_Bunny_Pulsar_C>();
	}
};

}

