#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_GaugeDeltaByValue

#include "Basic.hpp"


namespace SDK::Params
{

// Function SE_Bunny_GaugeDeltaByValue.SE_Bunny_GaugeDeltaByValue_C.GetTickRate
// 0x0008 (0x0008 - 0x0000)
struct SE_Bunny_GaugeDeltaByValue_C_GetTickRate final
{
public:
	double                                        TickRate;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

