#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_GaugeDeltaByMaxRatio

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1Data_structs.hpp"
#include "SE_Bunny_GaugeDeltaBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_Bunny_GaugeDeltaByMaxRatio.SE_Bunny_GaugeDeltaByMaxRatio_C
// 0x0018 (0x0370 - 0x0358)
class USE_Bunny_GaugeDeltaByMaxRatio_C : public USE_Bunny_GaugeDeltaBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_SE_Bunny_GaugeDeltaByMaxRatio_C;    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        RatePerSecond;                                     // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1StatType                                   GaugeMaxStatType;                                  // 0x0368(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bGaugeStatValid;                                   // 0x0369(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetTickRate(double* TickRate);
	void ExecuteUbergraph_SE_Bunny_GaugeDeltaByMaxRatio(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SE_Bunny_GaugeDeltaByMaxRatio_C">();
	}
	static class USE_Bunny_GaugeDeltaByMaxRatio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_Bunny_GaugeDeltaByMaxRatio_C>();
	}
};

}

