#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_Bunny_GaugeDeltaByValue

#include "Basic.hpp"

#include "SE_Bunny_GaugeDeltaByValue_classes.hpp"
#include "SE_Bunny_GaugeDeltaByValue_parameters.hpp"


namespace SDK
{

// Function SE_Bunny_GaugeDeltaByValue.SE_Bunny_GaugeDeltaByValue_C.GetTickRate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TickRate                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USE_Bunny_GaugeDeltaByValue_C::GetTickRate(double* TickRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SE_Bunny_GaugeDeltaByValue_C", "GetTickRate");

	Params::SE_Bunny_GaugeDeltaByValue_C_GetTickRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TickRate != nullptr)
		*TickRate = Parms.TickRate;
}

}

