#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SeasonReinforceAbility_Season_AllMoveSpeed

#include "Basic.hpp"

#include "SeasonReinforceAbility_Season_AllMoveSpeed_classes.hpp"
#include "SeasonReinforceAbility_Season_AllMoveSpeed_parameters.hpp"


namespace SDK
{

// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.OnAbilityEvent_67A689F44AFB1780E58CAB95CF755A71
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::OnAbilityEvent_67A689F44AFB1780E58CAB95CF755A71(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "OnAbilityEvent_67A689F44AFB1780E58CAB95CF755A71");

	Params::SeasonReinforceAbility_Season_AllMoveSpeed_C_OnAbilityEvent_67A689F44AFB1780E58CAB95CF755A71 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.OnAbilityDeactivated_E291E59E46B657E1F6E60EBC4D7AED77
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityId                     InAbilityId                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// class AActor*                           Owner                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bCanceled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::OnAbilityDeactivated_E291E59E46B657E1F6E60EBC4D7AED77(const struct FM1AbilityId& InAbilityId, const class AActor* Owner, bool bCanceled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "OnAbilityDeactivated_E291E59E46B657E1F6E60EBC4D7AED77");

	Params::SeasonReinforceAbility_Season_AllMoveSpeed_C_OnAbilityDeactivated_E291E59E46B657E1F6E60EBC4D7AED77 Parms{};

	Parms.InAbilityId = std::move(InAbilityId);
	Parms.Owner = Owner;
	Parms.bCanceled = bCanceled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.ExecuteUbergraph_SeasonReinforceAbility_Season_AllMoveSpeed
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::ExecuteUbergraph_SeasonReinforceAbility_Season_AllMoveSpeed(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "ExecuteUbergraph_SeasonReinforceAbility_Season_AllMoveSpeed");

	Params::SeasonReinforceAbility_Season_AllMoveSpeed_C_ExecuteUbergraph_SeasonReinforceAbility_Season_AllMoveSpeed Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.BP_OnCooltimeFinished
// (Event, Protected, BlueprintEvent)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::BP_OnCooltimeFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "BP_OnCooltimeFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USeasonReinforceAbility_Season_AllMoveSpeed_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SeasonReinforceAbility_Season_AllMoveSpeed_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

