#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SeasonReinforceAbility_Season_AllMoveSpeed

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SeasonReinforceAbility_Season_AllMoveSpeed.SeasonReinforceAbility_Season_AllMoveSpeed_C
// 0x0028 (0x02E0 - 0x02B8)
class USeasonReinforceAbility_Season_AllMoveSpeed_C final : public UM1SeasonReinforceAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FM1AbilityId                           InvokedSE;                                         // 0x02C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UM1AbilityTask_WaitAbilityEvent*        WaitAbilityEventTask;                              // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UM1AbilityTask_WaitAbilityDeactivated*  WaitSEEndTask;                                     // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Reset();
	void OnAbilityEvent_67A689F44AFB1780E58CAB95CF755A71(const struct FM1AbilityEvent& Event);
	void OnAbilityDeactivated_E291E59E46B657E1F6E60EBC4D7AED77(const struct FM1AbilityId& InAbilityId, const class AActor* Owner, bool bCanceled);
	void ExecuteUbergraph_SeasonReinforceAbility_Season_AllMoveSpeed(int32 EntryPoint);
	void BP_OnCooltimeFinished();
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SeasonReinforceAbility_Season_AllMoveSpeed_C">();
	}
	static class USeasonReinforceAbility_Season_AllMoveSpeed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USeasonReinforceAbility_Season_AllMoveSpeed_C>();
	}
};

}

