#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShockPunch_Rune

#include "Basic.hpp"

#include "Default_Fist_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShockPunch_Rune.ShockPunch_Rune_C
// 0x0000 (0x04F0 - 0x04F0)
class UShockPunch_Rune_C final : public UDefault_Fist_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShockPunch_Rune_C">();
	}
	static class UShockPunch_Rune_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShockPunch_Rune_C>();
	}
};

}

