#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active04

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "BunnyBeamLevelData_structs.hpp"
#include "M1_structs.hpp"
#include "Engine_structs.hpp"
#include "SkillAbility_BeamBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Bunny_Active04.Skill_Bunny_Active04_C
// 0x00E8 (0x04C0 - 0x03D8)
class USkill_Bunny_Active04_C final : public USkillAbility_BeamBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Skill_Bunny_Active04_C;             // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AM1Player*                              OwnerActor;                                        // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnBeamActivationChanged;                           // 0x03E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnBeamLevelIncrease;                               // 0x03F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	EM1BattleKey                                  BattleKey;                                         // 0x0408(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1StatType                                   CostStatType;                                      // 0x0409(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40A[0x6];                                      // 0x040A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBunnyBeamLevelData                    BeamLevelData_LV1;                                 // 0x0410(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChargeTime_Lv1;                                    // 0x0428(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChargeTime_Lv2;                                    // 0x0430(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DamageRate_Lv1;                                    // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DamageRate_Lv2;                                    // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DamageRate_Lv3;                                    // 0x0448(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBunnyBeamLevelData                    BeamLevelData_LV2;                                 // 0x0450(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBunnyBeamLevelData                    BeamLevelData_LV3;                                 // 0x0468(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bPlayingEndSection;                                // 0x0480(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsBeaming;                                        // 0x0481(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_482[0x6];                                      // 0x0482(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityId                           CostSEId;                                          // 0x0488(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         CurrBeamLevel;                                     // 0x0498(0x0004)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49C[0x4];                                      // 0x049C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           ChargeTimerHandle;                                 // 0x04A0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UM1DataVisualFX*                        VFXAsset;                                          // 0x04A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bCostDepleted;                                     // 0x04B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_WaitAbilityEvent*        WaitCostDepletedAsyncTask;                         // 0x04B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ServerOnReceiveEndInput();
	void OnMontageEventReceived(const struct FM1AbilityEvent& InEvent);
	void OnInput_B0EF358841BB5B69F2F99899295ECB10();
	void OnHit(const struct FHitResult& HitResult);
	void OnBeamLevelIncrease__DelegateSignature(int32 CurrentBeamLevel, double ChargeTimeToNextLevel, bool bMaxLevel);
	void OnBeamActivationChanged__DelegateSignature(bool bActivated);
	void OnAbilityEvent_4A462A1E4E1E7BE1AE84FA9C4E71DEA4(const struct FM1AbilityEvent& Event);
	void NetMulticastOnReceiveEndInput();
	void JumpEndSection();
	void IncreaseBeamLevel();
	void ExecuteUbergraph_Skill_Bunny_Active04(int32 EntryPoint);
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();
	void BeamStart();

	void GetBeamLevelData(int32 BeamLevel, struct FBunnyBeamLevelData* BeamLevelData, bool* bValid) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Bunny_Active04_C">();
	}
	static class USkill_Bunny_Active04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Bunny_Active04_C>();
	}
};

}

