#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active03

#include "Basic.hpp"

#include "Skill_Bunny_Active03_classes.hpp"
#include "Skill_Bunny_Active03_parameters.hpp"


namespace SDK
{

// Function Skill_Bunny_Active03.Skill_Bunny_Active03_C.ExecuteUbergraph_Skill_Bunny_Active03
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active03_C::ExecuteUbergraph_Skill_Bunny_Active03(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active03_C", "ExecuteUbergraph_Skill_Bunny_Active03");

	Params::Skill_Bunny_Active03_C_ExecuteUbergraph_Skill_Bunny_Active03 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active03.Skill_Bunny_Active03_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Bunny_Active03_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active03_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

