#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Passive

#include "Basic.hpp"

#include "Skill_Bunny_Passive_classes.hpp"
#include "Skill_Bunny_Passive_parameters.hpp"


namespace SDK
{

// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.UpdateLoopVFX
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::UpdateLoopVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "UpdateLoopVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.StartIncreaseGauge
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::StartIncreaseGauge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "StartIncreaseGauge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.StartHoldingGauge
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::StartHoldingGauge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "StartHoldingGauge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.StartDecreaseGauge
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::StartDecreaseGauge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "StartDecreaseGauge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Land Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Land_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Land Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Increase Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Increase_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Increase Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Hold Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Hold_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Hold Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Full Guage Leaving Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Full_Guage_Leaving_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Full Guage Leaving Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Full Guage Entering Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Full_Guage_Entering_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Full Guage Entering Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Decrease Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Decrease_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Decrease Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Deactivation Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Deactivation_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Deactivation Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Play Activation Sound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Play_Activation_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Play Activation Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::OnTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnTick");

	Params::Skill_Bunny_Passive_C_OnTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnStopMoving
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnStopMoving()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnStopMoving");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnStartMoving
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnStartMoving()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnStartMoving");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnRemovedStatus
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UM1StatusEffect*                  StatusEffect                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::OnRemovedStatus(const class UM1StatusEffect* StatusEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnRemovedStatus");

	Params::Skill_Bunny_Passive_C_OnRemovedStatus Parms{};

	Parms.StatusEffect = StatusEffect;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnLandingExplosion
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnLandingExplosion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnLandingExplosion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnFinish_0D2FCA1545A6896DE5C053835CFE4803
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnFinish_0D2FCA1545A6896DE5C053835CFE4803()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnFinish_0D2FCA1545A6896DE5C053835CFE4803");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnEvent_134BDA8C445F3F990A76638F4D6E5055
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     InTag                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    InAdded                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::OnEvent_134BDA8C445F3F990A76638F4D6E5055(const struct FGameplayTag& InTag, bool InAdded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnEvent_134BDA8C445F3F990A76638F4D6E5055");

	Params::Skill_Bunny_Passive_C_OnEvent_134BDA8C445F3F990A76638F4D6E5055 Parms{};

	Parms.InTag = std::move(InTag);
	Parms.InAdded = InAdded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnDoubleJump
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnDoubleJump()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnDoubleJump");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnDecreaseDelayFinished
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnDecreaseDelayFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnDecreaseDelayFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnDeboneDetached
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnDeboneDetached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnDeboneDetached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnDeboneAttached
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::OnDeboneAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnDeboneAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnChangedGauge
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EM1StatType                             StatType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::OnChangedGauge(EM1StatType StatType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnChangedGauge");

	Params::Skill_Bunny_Passive_C_OnChangedGauge Parms{};

	Parms.StatType = StatType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnAbilityEvent_7750724D4E64E3C330A5AFAE95BBCF70
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Passive_C::OnAbilityEvent_7750724D4E64E3C330A5AFAE95BBCF70(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnAbilityEvent_7750724D4E64E3C330A5AFAE95BBCF70");

	Params::Skill_Bunny_Passive_C_OnAbilityEvent_7750724D4E64E3C330A5AFAE95BBCF70 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.OnAbilityEvent_3C54BF444F4B2DFA3DDB0ABF06D3386E
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Passive_C::OnAbilityEvent_3C54BF444F4B2DFA3DDB0ABF06D3386E(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "OnAbilityEvent_3C54BF444F4B2DFA3DDB0ABF06D3386E");

	Params::Skill_Bunny_Passive_C_OnAbilityEvent_3C54BF444F4B2DFA3DDB0ABF06D3386E Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.MakeLandingExplosionParams
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     OpTag                                                  (Parm, OutParm, NoDestructor, HasGetValueTypeHash)
// struct FM1AbilityOperationParam         OpParam                                                (Parm, OutParm, ContainsInstancedReference)
// double                                  Radius                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             FXName                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::MakeLandingExplosionParams(struct FGameplayTag* OpTag, struct FM1AbilityOperationParam* OpParam, double* Radius, class FName* FXName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "MakeLandingExplosionParams");

	Params::Skill_Bunny_Passive_C_MakeLandingExplosionParams Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OpTag != nullptr)
		*OpTag = std::move(Parms.OpTag);

	if (OpParam != nullptr)
		*OpParam = std::move(Parms.OpParam);

	if (Radius != nullptr)
		*Radius = Parms.Radius;

	if (FXName != nullptr)
		*FXName = Parms.FXName;
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.IsStopMoving
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::IsStopMoving(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "IsStopMoving");

	Params::Skill_Bunny_Passive_C_IsStopMoving Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.IsStartMoving
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::IsStartMoving(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "IsStartMoving");

	Params::Skill_Bunny_Passive_C_IsStartMoving Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.IsMoving
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::IsMoving(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "IsMoving");

	Params::Skill_Bunny_Passive_C_IsMoving Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.Init
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.ExecuteUbergraph_Skill_Bunny_Passive
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::ExecuteUbergraph_Skill_Bunny_Passive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "ExecuteUbergraph_Skill_Bunny_Passive");

	Params::Skill_Bunny_Passive_C_ExecuteUbergraph_Skill_Bunny_Passive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.EndDecreaseAsyncTask
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::EndDecreaseAsyncTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "EndDecreaseAsyncTask");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.CheckOutStartedMovingOnce
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Passive_C::CheckOutStartedMovingOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "CheckOutStartedMovingOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Passive_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "BP_OnDeactivated");

	Params::Skill_Bunny_Passive_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Passive.Skill_Bunny_Passive_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Bunny_Passive_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Passive_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

