#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active02

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Bunny_Active02.Skill_Bunny_Active02_C
// 0x00B0 (0x03E8 - 0x0338)
class USkill_Bunny_Active02_C final : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AM1Player*                              Owner;                                             // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityId                           StatusEffectId_WhileActive;                        // 0x0348(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FM1AbilityId                           StatusEffectId_Moving_1;                           // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FM1AbilityId                           StatusEffectId_Moving_2;                           // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UM1AbilityTask_WaitAbilityEvent*        WaitCostDepletedAsyncTask;                         // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<EM1PlayerAnimType, class UClass*>        LocoAnimLayers;                                    // 0x0380(0x0050)(Edit, BlueprintVisible)
	bool                                          bWeaponChanging;                                   // 0x03D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D1[0x7];                                      // 0x03D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_WaitAbilityEvent*        WeaponChangeStartWaitTask;                         // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UM1AbilityTask_WaitAbilityEvent*        WeaponChangeEndWaitTask;                           // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void SetForceSprint(bool bForceSprint);
	void ServerOnReceiveToggleInput();
	void OnUpdate_A465146F451BCF37BB62B8B01618AE07(float DeltaTime);
	void OnTick();
	void OnInput_E1C054934884027A8F840AB031C1B55B();
	void OnAbilityEvent_D9CE56334E000AB66C54A5B3F5F494F7(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_BCB05C274186D253A5A233AB42192F94(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_31F5712C4DCC19F80D02CF8229DC721C(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_030F36AA4E14392ABD0E8B8A27E8923A(const struct FM1AbilityEvent& Event);
	void On_Changed_Player_Sprinting(bool bSprinting);
	void InvokeMovingStatusEffects();
	void Init();
	void ExecuteUbergraph_Skill_Bunny_Active02(int32 EntryPoint);
	void EndMovingStatusEffects();
	void Clear();
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();
	void ApplySprintCameraSetting();
	void ApplyLocomotionLayer();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Bunny_Active02_C">();
	}
	static class USkill_Bunny_Active02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Bunny_Active02_C>();
	}
};

}

