#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Passive

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "M1_structs.hpp"
#include "M1_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Bunny_Passive.Skill_Bunny_Passive_C
// 0x0080 (0x03B8 - 0x0338)
class USkill_Bunny_Passive_C final : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                LastVelocity;                                      // 0x0340(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34C[0x4];                                      // 0x034C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityId                           HolingStatusAbilityID;                             // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class AM1Player*                              OwnerCharacter;                                    // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        WaitingTimeToDecrease;                             // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UM1AbilityTask_WaitDelay*               DecreaseAsyncTask;                                 // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          HasJumpedTwice;                                    // 0x0378(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSkipHoldGague;                                   // 0x0379(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A[0x6];                                      // 0x037A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AOE_JumpSplashRadius;                              // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UM1DataVisualFX*                        LoopVFX;                                           // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bAppliedLoopVFX;                                   // 0x0390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        PrevGaugeRatio;                                    // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityId                           DecreaseSEId;                                      // 0x03A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          bDeboneAttached;                                   // 0x03B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateLoopVFX();
	void StartIncreaseGauge();
	void StartHoldingGauge();
	void StartDecreaseGauge();
	void Play_Land_Sound();
	void Play_Increase_Sound();
	void Play_Hold_Sound();
	void Play_Full_Guage_Leaving_Sound();
	void Play_Full_Guage_Entering_Sound();
	void Play_Decrease_Sound();
	void Play_Deactivation_Sound();
	void Play_Activation_Sound();
	void OnTick(float DeltaSeconds);
	void OnStopMoving();
	void OnStartMoving();
	void OnRemovedStatus(const class UM1StatusEffect* StatusEffect);
	void OnLandingExplosion();
	void OnFinish_0D2FCA1545A6896DE5C053835CFE4803();
	void OnEvent_134BDA8C445F3F990A76638F4D6E5055(const struct FGameplayTag& InTag, bool InAdded);
	void OnDoubleJump();
	void OnDecreaseDelayFinished();
	void OnDeboneDetached();
	void OnDeboneAttached();
	void OnChangedGauge(EM1StatType StatType);
	void OnAbilityEvent_7750724D4E64E3C330A5AFAE95BBCF70(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_3C54BF444F4B2DFA3DDB0ABF06D3386E(const struct FM1AbilityEvent& Event);
	void MakeLandingExplosionParams(struct FGameplayTag* OpTag, struct FM1AbilityOperationParam* OpParam, double* Radius, class FName* FXName);
	void IsStopMoving(bool* Result);
	void IsStartMoving(bool* Result);
	void IsMoving(bool* Result);
	void Init();
	void ExecuteUbergraph_Skill_Bunny_Passive(int32 EntryPoint);
	void EndDecreaseAsyncTask();
	void CheckOutStartedMovingOnce();
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Bunny_Passive_C">();
	}
	static class USkill_Bunny_Passive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Bunny_Passive_C>();
	}
};

}

