#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active03

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Bunny_Active03.Skill_Bunny_Active03_C
// 0x0028 (0x0360 - 0x0338)
class USkill_Bunny_Active03_C final : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  ForwardingOpTags;                                  // 0x0340(0x0020)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_Skill_Bunny_Active03(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Bunny_Active03_C">();
	}
	static class USkill_Bunny_Active03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Bunny_Active03_C>();
	}
};

}

