#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active01

#include "Basic.hpp"

#include "Skill_Bunny_Active01_classes.hpp"
#include "Skill_Bunny_Active01_parameters.hpp"


namespace SDK
{

// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.OnEventReceived_D24149544F57295232CAA18829AE84E5
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Active01_C::OnEventReceived_D24149544F57295232CAA18829AE84E5(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "OnEventReceived_D24149544F57295232CAA18829AE84E5");

	Params::Skill_Bunny_Active01_C_OnEventReceived_D24149544F57295232CAA18829AE84E5 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.OnCompleted_D24149544F57295232CAA18829AE84E5
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Active01_C::OnCompleted_D24149544F57295232CAA18829AE84E5(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "OnCompleted_D24149544F57295232CAA18829AE84E5");

	Params::Skill_Bunny_Active01_C_OnCompleted_D24149544F57295232CAA18829AE84E5 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.OnBlendOut_D24149544F57295232CAA18829AE84E5
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Active01_C::OnBlendOut_D24149544F57295232CAA18829AE84E5(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "OnBlendOut_D24149544F57295232CAA18829AE84E5");

	Params::Skill_Bunny_Active01_C_OnBlendOut_D24149544F57295232CAA18829AE84E5 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.NetMult_SpawnChainVFX
// (Net, NetMulticast, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AActor*>                   HitActors                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FVector>                  ServerHitLocs                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Active01_C::NetMult_SpawnChainVFX(const TArray<class AActor*>& HitActors, const TArray<struct FVector>& ServerHitLocs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "NetMult_SpawnChainVFX");

	Params::Skill_Bunny_Active01_C_NetMult_SpawnChainVFX Parms{};

	Parms.HitActors = std::move(HitActors);
	Parms.ServerHitLocs = std::move(ServerHitLocs);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.ExecuteUbergraph_Skill_Bunny_Active01
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active01_C::ExecuteUbergraph_Skill_Bunny_Active01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "ExecuteUbergraph_Skill_Bunny_Active01");

	Params::Skill_Bunny_Active01_C_ExecuteUbergraph_Skill_Bunny_Active01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Bunny_Active01_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active01.Skill_Bunny_Active01_C.Auth_ChainLightning
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active01_C::Auth_ChainLightning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active01_C", "Auth_ChainLightning");

	UObject::ProcessEvent(Func, nullptr);
}

}

