#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Bunny_Active04

#include "Basic.hpp"

#include "Skill_Bunny_Active04_classes.hpp"
#include "Skill_Bunny_Active04_parameters.hpp"


namespace SDK
{

// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.ServerOnReceiveEndInput
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::ServerOnReceiveEndInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "ServerOnReceiveEndInput");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnMontageEventReceived
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  InEvent                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void USkill_Bunny_Active04_C::OnMontageEventReceived(const struct FM1AbilityEvent& InEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnMontageEventReceived");

	Params::Skill_Bunny_Active04_C_OnMontageEventReceived Parms{};

	Parms.InEvent = std::move(InEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnInput_B0EF358841BB5B69F2F99899295ECB10
// (BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::OnInput_B0EF358841BB5B69F2F99899295ECB10()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnInput_B0EF358841BB5B69F2F99899295ECB10");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnHit
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FHitResult                       HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void USkill_Bunny_Active04_C::OnHit(const struct FHitResult& HitResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnHit");

	Params::Skill_Bunny_Active04_C_OnHit Parms{};

	Parms.HitResult = std::move(HitResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnBeamLevelIncrease__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentBeamLevel                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  ChargeTimeToNextLevel                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bMaxLevel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active04_C::OnBeamLevelIncrease__DelegateSignature(int32 CurrentBeamLevel, double ChargeTimeToNextLevel, bool bMaxLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnBeamLevelIncrease__DelegateSignature");

	Params::Skill_Bunny_Active04_C_OnBeamLevelIncrease__DelegateSignature Parms{};

	Parms.CurrentBeamLevel = CurrentBeamLevel;
	Parms.ChargeTimeToNextLevel = ChargeTimeToNextLevel;
	Parms.bMaxLevel = bMaxLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnBeamActivationChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bActivated                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active04_C::OnBeamActivationChanged__DelegateSignature(bool bActivated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnBeamActivationChanged__DelegateSignature");

	Params::Skill_Bunny_Active04_C_OnBeamActivationChanged__DelegateSignature Parms{};

	Parms.bActivated = bActivated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.OnAbilityEvent_4A462A1E4E1E7BE1AE84FA9C4E71DEA4
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Bunny_Active04_C::OnAbilityEvent_4A462A1E4E1E7BE1AE84FA9C4E71DEA4(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "OnAbilityEvent_4A462A1E4E1E7BE1AE84FA9C4E71DEA4");

	Params::Skill_Bunny_Active04_C_OnAbilityEvent_4A462A1E4E1E7BE1AE84FA9C4E71DEA4 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.NetMulticastOnReceiveEndInput
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::NetMulticastOnReceiveEndInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "NetMulticastOnReceiveEndInput");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.JumpEndSection
// (Private, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::JumpEndSection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "JumpEndSection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.IncreaseBeamLevel
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::IncreaseBeamLevel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "IncreaseBeamLevel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.ExecuteUbergraph_Skill_Bunny_Active04
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active04_C::ExecuteUbergraph_Skill_Bunny_Active04(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "ExecuteUbergraph_Skill_Bunny_Active04");

	Params::Skill_Bunny_Active04_C_ExecuteUbergraph_Skill_Bunny_Active04 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active04_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "BP_OnDeactivated");

	Params::Skill_Bunny_Active04_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Bunny_Active04_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.BeamStart
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Bunny_Active04_C::BeamStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "BeamStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Bunny_Active04.Skill_Bunny_Active04_C.GetBeamLevelData
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// int32                                   BeamLevel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FBunnyBeamLevelData              BeamLevelData                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bValid                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Bunny_Active04_C::GetBeamLevelData(int32 BeamLevel, struct FBunnyBeamLevelData* BeamLevelData, bool* bValid) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Bunny_Active04_C", "GetBeamLevelData");

	Params::Skill_Bunny_Active04_C_GetBeamLevelData Parms{};

	Parms.BeamLevel = BeamLevel;

	UObject::ProcessEvent(Func, &Parms);

	if (BeamLevelData != nullptr)
		*BeamLevelData = std::move(Parms.BeamLevelData);

	if (bValid != nullptr)
		*bValid = Parms.bValid;
}

}

