#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillAbility_BeamBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1Data_structs.hpp"
#include "M1_structs.hpp"
#include "M1_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SkillAbility_BeamBase.SkillAbility_BeamBase_C
// 0x00A0 (0x03D8 - 0x0338)
class USkillAbility_BeamBase_C : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bBeamStarted;                                      // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_341[0x7];                                      // 0x0341(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MontageTotalDuration;                              // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HitInterval;                                       // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ResetHitIntervalOnEscape;                          // 0x0358(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1BeamPenetrableType                         BeamPenetrableType;                                // 0x0359(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35A[0x2];                                      // 0x035A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   BeamCompTag;                                       // 0x035C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_364[0x4];                                      // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UM1BeamComponent*>               BeamComponents;                                    // 0x0368(0x0010)(Edit, BlueprintVisible, Transient, DisableEditOnInstance, ContainsInstancedReference)
	double                                        BeamLength;                                        // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UM1AbilityTask_PlayMontageAndWait*      AnimTask;                                          // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<struct FM1AbilityParamData>            HitOperationParam;                                 // 0x0388(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bDisableOtimization;                               // 0x0398(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_399[0x7];                                      // 0x0399(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  MontageWaitEvent;                                  // 0x03A0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        DebugDrawThickness;                                // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DebugDrawDuration;                                 // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDebugDraw;                                        // 0x03D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnMontageEventReceived(const struct FM1AbilityEvent& InEvent);
	void OnHit(const struct FHitResult& HitResult);
	void OnEventReceived_A43806C74BFC153D5719CE9AB981F899(const struct FM1AbilityEvent& Event);
	void OnEventReceived_8FDF88FA45348D44545A6FAC02900E80(const struct FM1AbilityEvent& Event);
	void OnCompleted_A43806C74BFC153D5719CE9AB981F899(const struct FM1AbilityEvent& Event);
	void OnCompleted_8FDF88FA45348D44545A6FAC02900E80(const struct FM1AbilityEvent& Event);
	void OnChangeBeamComp(class FName NewBeamCompTag);
	void OnBlendOut_A43806C74BFC153D5719CE9AB981F899(const struct FM1AbilityEvent& Event);
	void OnBlendOut_8FDF88FA45348D44545A6FAC02900E80(const struct FM1AbilityEvent& Event);
	void InitBeamComponents();
	void ExecuteUbergraph_SkillAbility_BeamBase(int32 EntryPoint);
	void ChangeBeamTag(class FName BeamTag);
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();
	void BeamStart();
	void BeamEnd();

	void GetMontageDuration(double* OutDuration) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SkillAbility_BeamBase_C">();
	}
	static class USkillAbility_BeamBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkillAbility_BeamBase_C>();
	}
};

}

