#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Lepic_Rune05_Passive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Lepic_Rune05_Passive.Skill_Lepic_Rune05_Passive_C
// 0x0030 (0x0368 - 0x0338)
class USkill_Lepic_Rune05_Passive_C final : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  SkillCommitededEventTags;                          // 0x0340(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        MpRecoveryRate;                                    // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnAbilityEvent_CB49F57544211ED579D4EFBD2DEAE2DC(const struct FM1AbilityEvent& Event);
	void ExecuteUbergraph_Skill_Lepic_Rune05_Passive(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Lepic_Rune05_Passive_C">();
	}
	static class USkill_Lepic_Rune05_Passive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Lepic_Rune05_Passive_C>();
	}
};

}

