#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Lepic_Rune05_Passive

#include "Basic.hpp"

#include "Skill_Lepic_Rune05_Passive_classes.hpp"
#include "Skill_Lepic_Rune05_Passive_parameters.hpp"


namespace SDK
{

// Function Skill_Lepic_Rune05_Passive.Skill_Lepic_Rune05_Passive_C.OnAbilityEvent_CB49F57544211ED579D4EFBD2DEAE2DC
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Lepic_Rune05_Passive_C::OnAbilityEvent_CB49F57544211ED579D4EFBD2DEAE2DC(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Lepic_Rune05_Passive_C", "OnAbilityEvent_CB49F57544211ED579D4EFBD2DEAE2DC");

	Params::Skill_Lepic_Rune05_Passive_C_OnAbilityEvent_CB49F57544211ED579D4EFBD2DEAE2DC Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Lepic_Rune05_Passive.Skill_Lepic_Rune05_Passive_C.ExecuteUbergraph_Skill_Lepic_Rune05_Passive
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Lepic_Rune05_Passive_C::ExecuteUbergraph_Skill_Lepic_Rune05_Passive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Lepic_Rune05_Passive_C", "ExecuteUbergraph_Skill_Lepic_Rune05_Passive");

	Params::Skill_Lepic_Rune05_Passive_C_ExecuteUbergraph_Skill_Lepic_Rune05_Passive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Lepic_Rune05_Passive.Skill_Lepic_Rune05_Passive_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Lepic_Rune05_Passive_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Lepic_Rune05_Passive_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

