#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Perk_Greatlegacy

#include "Basic.hpp"

#include "StatusEffect_Perk_Greatlegacy_classes.hpp"
#include "StatusEffect_Perk_Greatlegacy_parameters.hpp"


namespace SDK
{

// Function StatusEffect_Perk_Greatlegacy.StatusEffect_Perk_Greatlegacy_C.ExecuteUbergraph_StatusEffect_Perk_Greatlegacy
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStatusEffect_Perk_Greatlegacy_C::ExecuteUbergraph_StatusEffect_Perk_Greatlegacy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatusEffect_Perk_Greatlegacy_C", "ExecuteUbergraph_StatusEffect_Perk_Greatlegacy");

	Params::StatusEffect_Perk_Greatlegacy_C_ExecuteUbergraph_StatusEffect_Perk_Greatlegacy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatusEffect_Perk_Greatlegacy.StatusEffect_Perk_Greatlegacy_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UStatusEffect_Perk_Greatlegacy_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatusEffect_Perk_Greatlegacy_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

