#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Poison

#include "Basic.hpp"

#include "SimpleStatusEffect_VFXPlay_classes.hpp"


namespace SDK
{

}

