#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Perk_Greatlegacy

#include "Basic.hpp"


namespace SDK::Params
{

// Function StatusEffect_Perk_Greatlegacy.StatusEffect_Perk_Greatlegacy_C.ExecuteUbergraph_StatusEffect_Perk_Greatlegacy
// 0x0018 (0x0018 - 0x0000)
struct StatusEffect_Perk_Greatlegacy_C_ExecuteUbergraph_StatusEffect_Perk_Greatlegacy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UNiagaraComponent*>              CallFunc_SpawnFXsForAbility_ReturnValue;           // 0x0008(0x0010)(ReferenceParm, ContainsInstancedReference)
};

}

