#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatusEffect_Perk_Greatlegacy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StatusEffect_Perk_Greatlegacy.StatusEffect_Perk_Greatlegacy_C
// 0x0008 (0x0388 - 0x0380)
class UStatusEffect_Perk_Greatlegacy_C final : public UM1SimpleStatusEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_StatusEffect_Perk_Greatlegacy(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StatusEffect_Perk_Greatlegacy_C">();
	}
	static class UStatusEffect_Perk_Greatlegacy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStatusEffect_Perk_Greatlegacy_C>();
	}
};

}

