#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Codex_FocusGoal_Task_Item

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Codex_FocusGoal_Task_Item.UI_Codex_FocusGoal_Task_Item_C
// 0x0010 (0x0738 - 0x0728)
class UUI_Codex_FocusGoal_Task_Item_C final : public UM1UIGameCodexFocusGoalDetailSlot
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0728(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       UIAnim_Gain;                                       // 0x0730(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void SetUI_Complete_Color(bool In_complete);
	void SequenceEvent__ENTRYPOINTUI_Codex_FocusGoal_Task_Item();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_Codex_FocusGoal_Task_Item(int32 EntryPoint);
	void BP_widget_playAkEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Codex_FocusGoal_Task_Item_C">();
	}
	static class UUI_Codex_FocusGoal_Task_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Codex_FocusGoal_Task_Item_C>();
	}
};

}

