#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Codex_Tracking_Task_Item

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Codex_Tracking_Task_Item.UI_Codex_Tracking_Task_Item_C
// 0x0008 (0x0730 - 0x0728)
class UUI_Codex_Tracking_Task_Item_C final : public UM1UIGameCodexTrackingDetailSlot
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0728(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void SetUI_Complete_Color(bool In_complete);
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_Codex_Tracking_Task_Item(int32 EntryPoint);
	void BP_widget_playAkEvent(class UAkAudioEvent* AkEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Codex_Tracking_Task_Item_C">();
	}
	static class UUI_Codex_Tracking_Task_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Codex_Tracking_Task_Item_C>();
	}
};

}

