#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SkillCustomHUD_BunnyActive4

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C
// 0x0060 (0x0778 - 0x0718)
class UUI_SkillCustomHUD_BunnyActive4_C final : public UM1UISkillCustomHUD
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0718(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ANIM_ChargingTimeProgress_Charge_3;                // 0x0720(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ANIM_ChargingTimeProgress_Charge_2;                // 0x0728(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ANIM_ChargingTimeProgress_Charge_1;                // 0x0730(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_SkillCustomHUD_BunnyActive4_Item_C* BeamLv_1;                                          // 0x0738(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_SkillCustomHUD_BunnyActive4_Item_C* BeamLv_2;                                          // 0x0740(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_SkillCustomHUD_BunnyActive4_Item_C* BeamLv_3;                                          // 0x0748(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           RootPanel;                                         // 0x0750(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USkill_Bunny_Active04_C*                SkillAbilityRef;                                   // 0x0758(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UUI_SkillCustomHUD_BunnyActive4_Item_C*> BeamLvWidgets;                                     // 0x0760(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UWidgetAnimation*                       CurrWidgetAnim;                                    // 0x0770(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateBeamLevelGauge(int32 BeamLevel, double GaugePrecentage);
	void ShowWidget(bool bShow);
	void ResetWidgetVisibilities();
	void OnBeamLevelIncrease(int32 BeamLevel, double ChargeTimeToNextLevel, bool bMaxLevel);
	void ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4(int32 EntryPoint);
	void Destruct();
	void Construct();
	void BP_OnSkillDeactivated();
	void BP_OnSkillActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SkillCustomHUD_BunnyActive4_C">();
	}
	static class UUI_SkillCustomHUD_BunnyActive4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SkillCustomHUD_BunnyActive4_C>();
	}
};

}

