#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SkillCustomHUD_BunnyActive4_Item

#include "Basic.hpp"

#include "UI_SkillCustomHUD_BunnyActive4_Item_classes.hpp"
#include "UI_SkillCustomHUD_BunnyActive4_Item_parameters.hpp"


namespace SDK
{

// Function UI_SkillCustomHUD_BunnyActive4_Item.UI_SkillCustomHUD_BunnyActive4_Item_C.UISetDefault
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_SkillCustomHUD_BunnyActive4_Item_C::UISetDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_SkillCustomHUD_BunnyActive4_Item_C", "UISetDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_SkillCustomHUD_BunnyActive4_Item.UI_SkillCustomHUD_BunnyActive4_Item_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_SkillCustomHUD_BunnyActive4_Item_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_SkillCustomHUD_BunnyActive4_Item_C", "PreConstruct");

	Params::UI_SkillCustomHUD_BunnyActive4_Item_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_SkillCustomHUD_BunnyActive4_Item.UI_SkillCustomHUD_BunnyActive4_Item_C.ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4_Item
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_SkillCustomHUD_BunnyActive4_Item_C::ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4_Item(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_SkillCustomHUD_BunnyActive4_Item_C", "ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4_Item");

	Params::UI_SkillCustomHUD_BunnyActive4_Item_C_ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4_Item Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

