#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SkillIconCustom_BunnyPassive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1Data_structs.hpp"
#include "M1_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SkillIconCustom_BunnyPassive.UI_SkillIconCustom_BunnyPassive_C
// 0x0020 (0x0738 - 0x0718)
class UUI_SkillIconCustom_BunnyPassive_C final : public UM1UIActionIcon_CustomWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0718(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ANIM_Bunny_PassiveSkillMaxOn;                      // 0x0720(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               Panel_Bunny_PassiveSkill_MaxOn;                    // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bFull;                                             // 0x0730(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void SetDataImpl(class UM1UIData* InData);
	void OnChangedCommonGauge(EM1StatType StatType);
	void ExecuteUbergraph_UI_SkillIconCustom_BunnyPassive(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SkillIconCustom_BunnyPassive_C">();
	}
	static class UUI_SkillIconCustom_BunnyPassive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SkillIconCustom_BunnyPassive_C>();
	}
};

}

