name: Build C++ Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Build the project
    - name: Build Solution
      run: msbuild TFDInternal.sln /p:Configuration=Debug
