name: Build and Release TFD Internal C++ Project

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Build the project
    - name: Build Solution
      run: msbuild DescendantInternal.sln /p:Configuration=Release

    # Step 4: Create a release with the latest commit message as notes
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # Step 5: Upload the built artifact to the release
    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: x64\Release\DescendantInternal.dll
        asset_name: DescendantInternal.dll
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
