name: Build and Release C++ Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up MSBuild environment
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    # Step 3: Build the project
    - name: Build Solution
      run: msbuild DescendantInternal.sln /p:Configuration=Release

    - name: List Files in Output Directory
      run: dir x64\Release

    # Step 4: Archive build artifacts (optional)
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: x64\Release
        
    # Step 5: Create GitHub Release and Upload Asset
    - name: Create GitHub Release with Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }} # Replace with your versioning logic
        name: Release v1.0.${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        files: x64/Release/DescendantInternal.dll
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
